// Curated ad and pop-under hosts. Subdomains are matched automatically.
// Keep this list sorted and unique; test/match.test.js enforces that.
globalThis.BLOCKEE_AD_DOMAINS = [
  "2mdn.net",
  "3lift.com",
  "ad-maven.com",
  "adblade.com",
  "adcash.com",
  "adform.com",
  "adform.net",
  "adition.com",
  "admaven.com",
  "adnxs.com",
  "adoperator.com",
  "adroll.com",
  "ads.yahoo.com",
  "adsafeprotected.com",
  "adservice.google.com",
  "adskeeper.com",
  "adsrvr.org",
  "adsterra.com",
  "adsymptotic.com",
  "adtech.de",
  "adtechus.com",
  "advertising.com",
  "amazon-adsystem.com",
  "aniview.com",
  "bidr.io",
  "bidswitch.net",
  "casalemedia.com",
  "clickadu.com",
  "clickaine.com",
  "connatix.com",
  "content.ad",
  "contextweb.com",
  "criteo.com",
  "criteo.net",
  "doubleclick.net",
  "doubleverify.com",
  "evadav.com",
  "exoclick.com",
  "exosrv.com",
  "flashtalking.com",
  "friseurash.com",
  "galaksion.com",
  "googleadservices.com",
  "googlesyndication.com",
  "googletagservices.com",
  "hilltopads.com",
  "hilltopads.net",
  "imasdk.googleapis.com",
  "indexww.com",
  "iniquegearbox.com",
  "juicyads.com",
  "lijit.com",
  "lockerdome.com",
  "mathtag.com",
  "media.net",
  "mgid.com",
  "moatads.com",
  "monetag.com",
  "nativo.com",
  "onclickads.net",
  "onclkds.com",
  "openx.com",
  "openx.net",
  "outbrain.com",
  "popads.net",
  "popcash.net",
  "popmyads.com",
  "popunder.net",
  "primis.tech",
  "propellerads.com",
  "pubmatic.com",
  "revcontent.com",
  "richads.com",
  "rubiconproject.com",
  "seedtag.com",
  "serving-sys.com",
  "sharethrough.com",
  "sitescout.com",
  "sizmek.com",
  "smartadserver.com",
  "smartclip.net",
  "sonobi.com",
  "sovrn.com",
  "spotx.tv",
  "spotxchange.com",
  "stickyadstv.com",
  "taboola.com",
  "teads.tv",
  "trafficjunky.com",
  "trafficjunky.net",
  "trafficstars.com",
  "triplelift.com",
  "turn.com",
  "vidoomy.com",
  "weborama.fr",
  "yieldmo.com",
  "zemanta.com",
  "zergnet.com",
];

// Path rules for ad endpoints that live on otherwise legitimate hosts.
// Pop-under tags look like https://random-host.example/Token/140399
globalThis.BLOCKEE_POP_SCRIPT_PATH = "^/[A-Za-z0-9_-]{10,}/[0-9]{5,7}/?$";

globalThis.BLOCKEE_AD_PATHS = [
  { host: "google.com", path: "/aclk" },
  { host: "google.com", path: "/adsense/" },
  { host: "google.com", path: "/pagead" },
  { host: "gstatic.com", path: "/ads/" },
  { host: "youtube.com", path: "/api/stats/ads" },
  { host: "youtube.com", path: "/get_midroll_" },
  { host: "youtube.com", path: "/pagead" },
  { host: "youtube.com", path: "/ptracking" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    BLOCKEE_AD_DOMAINS: globalThis.BLOCKEE_AD_DOMAINS,
    BLOCKEE_AD_PATHS: globalThis.BLOCKEE_AD_PATHS,
    BLOCKEE_POP_SCRIPT_PATH: globalThis.BLOCKEE_POP_SCRIPT_PATH,
  };
}
